### ISSUE TITLE
Find a Game Channel

### ISSUE THREAD

**Issue by RykerCohen** [biaw/the-impostor#10]
There will be a voice channel called 'Click to find a party' which when a user clicks it, it looks for an available game channel that isn't full and moves a user there

**Comment by promise** [comment]
The thing about the bot is that it can only handle 10 people at once... it's not really ideal to host more than five games at once, because it gets rate limited whenever there are more than 10 people playing at the same time. TBD.

**Comment by RykerCohen** [comment]
Ah. If it could work for multiple games, that would be cool for community type servers

**Comment by promise** [comment]
Closing this because the bot is not meant for multiple lobbies... and you can also just scroll through the voice channels and see if there's a lobby around.
