### ISSUE TITLE
Voice Channel Invite Links

### ISSUE THREAD

**Issue by RykerCohen** [biaw/the-impostor#12]
# Feature request

Have the bot DM the user voice channel invite links to send to friends or other people. More useful in bigger servers.

**Comment by promise** [comment]
The thing is, it's not really meant to be used in bigger servers, since it can only handle 10 people at once... But I do see that people would like this, and I'm gonna see if I can figure out a better system for this.

**Comment by promise** [comment]
Closing this as the host can rather just make a new temporary server and invite the bot and send an invite to the players.
