### ISSUE TITLE
A proper help menu 

### ISSUE THREAD

**Issue by Aditya20-ai** [biaw/the-impostor#3]
![image](https://user-images.githubusercontent.com/71256476/93075166-09a2fc80-f6a3-11ea-8616-149c6dbefb1e.png)
This image is the current help response by the bot imposter , i feel that the bot can send this message as its first message when its invited by the user.
there are commands in the bot like ping and info which are not directly said in the help menu .

 so for clarity would like a help commandby the bot which embeds with two fields 1. setup and 2. other in the help command , this would be easier for people who dont know that the commands exist . 

i would also like to have a seperate support command instead of cramming it with the help command `im!support` - which leads to the support server.

**Comment by promise** [comment]
If someone wants to make this, feel free to PR. If not, I'll make it in October :)
