### ISSUE TITLE
Bugged Game Deletion

### ISSUE THREAD

**Issue by e5510** [biaw/the-impostor#30]
# Bug Report

Channels aren’t deleted unless the leave channel button is pressed..

## Reproducing

1. Join the create a new game voice channel.
2. After moved to (usernames) game rejoin the create a new game Voice channel.
3. Continue until server runs out of voice channel slots or you get bored.

## Expected behavior
As nobody else is in the channel, delete the channel.

**Comment by amyhlback** [comment]
I could not reproduce that, for me it deletes the game vc as soon as the last member leaves.

(switching channel, starting a new game, leaving vc, leaving a game vc another person started and left etc)

**Comment by e5510** [comment]
> I could not reproduce that, for me it deletes the game vc as soon as the last member leaves.
> 
> (switching channel, starting a new game, leaving vc, leaving a game vc another person started and left etc)

Yeah, this works. Joining create game, then getting moved to the game then joint create game again however doesn’t delete it if someone doesn’t perform the leave action. https://share.getcloudapp.com/RBu9dXzL

**Comment by amyhlback** [comment]
> Yeah, this works. Joining create game, then getting moved to the game then joining create game again however doesn’t delete it if someone doesn’t perform the leave action. https://share.getcloudapp.com/RBu9dXzL

That's what i tested also, and could not recreate.
But it was done on my old testserver where i have messed around with permissions a bit, so everything working fine is probably related to that.

On a new server created today the bugged behavior is indeed there:
![discord_new](https://user-images.githubusercontent.com/11929153/100997838-12e18e00-355b-11eb-9a5d-96f65dd7f21b.gif)

However, just enabling "Manage Permissions"-permission for the bot on the "Among Us" category fixes it:
![discord_new_fixed](https://user-images.githubusercontent.com/11929153/100998302-9f8c4c00-355b-11eb-8552-006a09078e58.gif)

Enabling that permission also fixes hosts not being given "Server Mute" capability for their own game vc.
